apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: nginx-dedicated-school
  ports:
  - protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: 80